package de.maxhenkel.car.entity.model.transporter;

import de.maxhenkel.car.entity.car.base.EntityCarBase;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransporter extends ModelBase {

	private ModelRenderer bottom;
	private ModelRenderer wheel1a;
	private ModelRenderer wheel1b;
	private ModelRenderer wheel1c;
	private ModelRenderer wheel1d;
	private ModelRenderer wheel1e;
	private ModelRenderer wheel1f;
	private ModelRenderer wheel1g;
	private ModelRenderer wheel2a;
	private ModelRenderer wheel2b;
	private ModelRenderer wheel2c;
	private ModelRenderer wheel2d;
	private ModelRenderer wheel2e;
	private ModelRenderer wheel2f;
	private ModelRenderer wheel2g;
	private ModelRenderer wheel3a;
	private ModelRenderer wheel3b;
	private ModelRenderer wheel3c;
	private ModelRenderer wheel3d;
	private ModelRenderer wheel3e;
	private ModelRenderer wheel3f;
	private ModelRenderer wheel3g;
	private ModelRenderer wheel4a;
	private ModelRenderer wheel4b;
	private ModelRenderer wheel4c;
	private ModelRenderer wheel4d;
	private ModelRenderer wheel4e;
	private ModelRenderer wheel4f;
	private ModelRenderer wheel4g;
	private ModelRenderer wheel5a;
	private ModelRenderer wheel5b;
	private ModelRenderer wheel5c;
	private ModelRenderer wheel5d;
	private ModelRenderer wheel5e;
	private ModelRenderer wheel5f;
	private ModelRenderer wheel5g;
	private ModelRenderer wheel6a;
	private ModelRenderer wheel6b;
	private ModelRenderer wheel6c;
	private ModelRenderer wheel6d;
	private ModelRenderer wheel6e;
	private ModelRenderer wheel6f;
	private ModelRenderer wheel6g;
	private ModelRenderer front;
	private ModelRenderer frontWindow;
	private ModelRenderer backWindow;
	private ModelRenderer topLoader;
	private ModelRenderer back;
	private ModelRenderer right;
	private ModelRenderer left;
	private ModelRenderer leftFront;
	private ModelRenderer rightFront;
	private ModelRenderer rightTop;
	private ModelRenderer leftTop;
	private ModelRenderer topFront;
	private ModelRenderer hood;
	private ModelRenderer cabinLower;
	private ModelRenderer container;
	private boolean con;

	public ModelTransporter(boolean con) {
		this.con=con;
		
		textureWidth = 128;
		textureHeight = 256;

		this.leftTop = new ModelRenderer(this, 0, 118);
        this.leftTop.setRotationPoint(13.0F, -8.0F, 5.0F);
        this.leftTop.addBox(-1.0F, -9.0F, 0.0F, 1, 9, 12);
        this.leftTop.mirror = true;
        this.setRotation(this.leftTop, 0.0F, 0.0F, 3.141592653589793F);
        this.rightFront = new ModelRenderer(this, 0, 142);
        this.rightFront.setRotationPoint(-14.0F, -18.0F, 5.0F);
        this.rightFront.addBox(0.0F, 0.0F, 0.0F, 1, 10, 15);
        this.rightFront.mirror = true;
        this.wheel3d = new ModelRenderer(this, 12, 0);
        this.wheel3d.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3d.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel3d.mirror = true;
        this.topLoader = new ModelRenderer(this, 0, 59);
        this.topLoader.setRotationPoint(-13.0F, -13.0F, -16.0F);
        this.topLoader.addBox(0.0F, 0.0F, 0.0F, 26, 1, 20);
        this.topLoader.mirror = true;
        this.wheel3e = new ModelRenderer(this, 18, 2);
        this.wheel3e.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3e.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel3e.mirror = true;
        this.leftFront = new ModelRenderer(this, 47, 142);
        this.leftFront.setRotationPoint(13.0F, -18.0F, 5.0F);
        this.leftFront.addBox(0.0F, 0.0F, 0.0F, 1, 10, 15);
        this.leftFront.mirror = true;
        this.wheel3f = new ModelRenderer(this, 4, 3);
        this.wheel3f.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3f.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel3f.mirror = true;
        this.wheel3g = new ModelRenderer(this, 26, 4);
        this.wheel3g.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3g.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel3g.mirror = true;
        this.wheel3a = new ModelRenderer(this, 26, 4);
        this.wheel3a.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3a.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel3a.mirror = true;
        this.wheel3b = new ModelRenderer(this, 4, 3);
        this.wheel3b.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3b.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel3b.mirror = true;
        this.cabinLower = new ModelRenderer(this, 0, 170);
        this.cabinLower.setRotationPoint(-14.0F, -18.0F, 4.0F);
        this.cabinLower.addBox(0.0F, 0.0F, 0.0F, 28, 6, 1);
        this.cabinLower.mirror = true;
        this.wheel3c = new ModelRenderer(this, 18, 2);
        this.wheel3c.setRotationPoint(14.0F, -18.0F, 13.0F);
        this.wheel3c.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel3c.mirror = true;
        this.bottom = new ModelRenderer(this, 34, 0);
        this.bottom.setRotationPoint(-14.0F, -18.0F, 11.0F);
        this.bottom.addBox(0.0F, -1.0F, -28.0F, 28, 1, 38);
        this.bottom.mirror = true;
        this.wheel2g = new ModelRenderer(this, 8, 2);
        this.wheel2g.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2g.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel2g.mirror = true;
        this.hood = new ModelRenderer(this, 0, 237);
        this.hood.setRotationPoint(-13.0F, -9.0F, 18.0F);
        this.hood.addBox(0.0F, 0.0F, 0.0F, 26, 1, 2);
        this.hood.mirror = true;
        this.wheel2c = new ModelRenderer(this, 22, 3);
        this.wheel2c.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2c.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel2c.mirror = true;
        this.wheel6g = new ModelRenderer(this, 18, 2);
        this.wheel6g.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6g.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel6g.mirror = true;
        this.wheel2d = new ModelRenderer(this, 0, 4);
        this.wheel2d.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2d.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel2d.mirror = true;
        this.wheel2e = new ModelRenderer(this, 26, 4);
        this.wheel2e.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2e.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel2e.mirror = true;
        this.wheel2f = new ModelRenderer(this, 4, 3);
        this.wheel2f.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2f.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel2f.mirror = true;
        this.wheel6c = new ModelRenderer(this, 4, 3);
        this.wheel6c.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6c.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel6c.mirror = true;
        this.wheel6d = new ModelRenderer(this, 0, 4);
        this.wheel6d.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6d.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel6d.mirror = true;
        this.left = new ModelRenderer(this, 47, 81);
        this.left.setRotationPoint(13.0F, -18.0F, -17.0F);
        this.left.addBox(-1.0F, -13.0F, 0.0F, 1, 13, 21);
        this.left.mirror = true;
        this.setRotation(this.left, 0.0F, 0.0F, 3.141592653589793F);
        this.wheel2a = new ModelRenderer(this, 18, 2);
        this.wheel2a.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2a.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel2a.mirror = true;
        this.wheel6e = new ModelRenderer(this, 26, 4);
        this.wheel6e.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6e.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel6e.mirror = true;
        this.wheel2b = new ModelRenderer(this, 12, 0);
        this.wheel2b.setRotationPoint(-15.0F, -18.0F, -5.0F);
        this.wheel2b.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel2b.mirror = true;
        this.wheel6f = new ModelRenderer(this, 22, 3);
        this.wheel6f.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6f.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel6f.mirror = true;
        this.wheel6a = new ModelRenderer(this, 8, 2);
        this.wheel6a.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6a.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel6a.mirror = true;
        this.wheel6b = new ModelRenderer(this, 12, 0);
        this.wheel6b.setRotationPoint(14.0F, -18.0F, -13.0F);
        this.wheel6b.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel6b.mirror = true;
        this.back = new ModelRenderer(this, 0, 28);
        this.back.setRotationPoint(-13.0F, -18.0F, -17.0F);
        this.back.addBox(0.0F, 0.0F, 0.0F, 26, 6, 1);
        this.back.mirror = true;
        this.wheel1f = new ModelRenderer(this, 22, 3);
        this.wheel1f.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1f.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel1f.mirror = true;
        this.wheel1g = new ModelRenderer(this, 18, 2);
        this.wheel1g.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1g.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel1g.mirror = true;
        this.wheel1b = new ModelRenderer(this, 12, 0);
        this.wheel1b.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1b.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel1b.mirror = true;
        this.wheel5f = new ModelRenderer(this, 4, 3);
        this.wheel5f.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5f.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel5f.mirror = true;
        this.wheel1c = new ModelRenderer(this, 4, 3);
        this.wheel1c.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1c.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel1c.mirror = true;
        this.wheel5g = new ModelRenderer(this, 8, 2);
        this.wheel5g.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5g.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel5g.mirror = true;
        this.wheel1d = new ModelRenderer(this, 0, 4);
        this.wheel1d.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1d.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel1d.mirror = true;
        this.wheel1e = new ModelRenderer(this, 26, 4);
        this.wheel1e.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1e.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel1e.mirror = true;
        this.wheel5b = new ModelRenderer(this, 12, 0);
        this.wheel5b.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5b.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel5b.mirror = true;
        this.wheel5c = new ModelRenderer(this, 22, 3);
        this.wheel5c.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5c.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel5c.mirror = true;
        this.wheel5d = new ModelRenderer(this, 0, 4);
        this.wheel5d.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5d.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel5d.mirror = true;
        this.wheel1a = new ModelRenderer(this, 8, 2);
        this.wheel1a.setRotationPoint(14.0F, -18.0F, -5.0F);
        this.wheel1a.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel1a.mirror = true;
        this.wheel5e = new ModelRenderer(this, 26, 4);
        this.wheel5e.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5e.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel5e.mirror = true;
        this.wheel5a = new ModelRenderer(this, 18, 2);
        this.wheel5a.setRotationPoint(-15.0F, -18.0F, -13.0F);
        this.wheel5a.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel5a.mirror = true;
        this.topFront = new ModelRenderer(this, 0, 180);
        this.topFront.setRotationPoint(-13.0F, 0.0F, 5.0F);
        this.topFront.addBox(0.0F, 0.0F, 0.0F, 26, 1, 12);
        this.topFront.mirror = true;
        this.right = new ModelRenderer(this, 0, 81);
        this.right.setRotationPoint(-14.0F, -18.0F, -17.0F);
        this.right.addBox(-1.0F, -13.0F, 0.0F, 1, 13, 21);
        this.right.mirror = true;
        this.setRotation(this.right, 0.0F, 0.0F, 3.141592653589793F);
        this.wheel4e = new ModelRenderer(this, 8, 2);
        this.wheel4e.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4e.addBox(0.0F, -3.0F, 1.0F, 1, 6, 1);
        this.wheel4e.mirror = true;
        this.wheel4f = new ModelRenderer(this, 22, 3);
        this.wheel4f.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4f.addBox(0.0F, -2.0F, 2.0F, 1, 4, 1);
        this.wheel4f.mirror = true;
        this.wheel4g = new ModelRenderer(this, 0, 4);
        this.wheel4g.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4g.addBox(0.0F, -1.0F, 3.0F, 1, 2, 1);
        this.wheel4g.mirror = true;
        this.wheel4a = new ModelRenderer(this, 26, 4);
        this.wheel4a.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4a.addBox(0.0F, -1.0F, -4.0F, 1, 2, 1);
        this.wheel4a.mirror = true;
        this.wheel4b = new ModelRenderer(this, 22, 3);
        this.wheel4b.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4b.addBox(0.0F, -2.0F, -3.0F, 1, 4, 1);
        this.wheel4b.mirror = true;
        this.wheel4c = new ModelRenderer(this, 8, 2);
        this.wheel4c.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4c.addBox(0.0F, -3.0F, -2.0F, 1, 6, 1);
        this.wheel4c.mirror = true;
        this.wheel4d = new ModelRenderer(this, 12, 0);
        this.wheel4d.setRotationPoint(-15.0F, -18.0F, 13.0F);
        this.wheel4d.addBox(0.0F, -4.0F, -1.0F, 1, 8, 2);
        this.wheel4d.mirror = true;
        this.front = new ModelRenderer(this, 0, 242);
        this.front.setRotationPoint(-14.0F, -18.0F, 20.0F);
        this.front.addBox(0.0F, -10.0F, -1.0F, 28, 10, 1);
        this.front.mirror = true;
        this.setRotation(this.front, 3.141592653589793F, 0.0F, 0.0F);
        this.backWindow = new ModelRenderer(this, 0, 41);
        this.backWindow.setRotationPoint(-14.0F, -12.0F, 4.0F);
        this.backWindow.addBox(0.0F, 0.0F, 0.0F, 28, 13, 1);
        this.backWindow.mirror = true;
        this.frontWindow = new ModelRenderer(this, 0, 15);
        this.frontWindow.setRotationPoint(-14.0F, -8.0F, 17.0F);
        this.frontWindow.addBox(-28.0F, -9.0F, 0.0F, 28, 9, 1);
        this.frontWindow.mirror = true;
        this.setRotation(this.frontWindow, 0.0F, 0.0F, 3.141592653589793F);
        this.rightTop = new ModelRenderer(this, 47, 118);
        this.rightTop.setRotationPoint(-14.0F, -8.0F, 5.0F);
        this.rightTop.addBox(-1.0F, -9.0F, 0.0F, 1, 9, 12);
        this.rightTop.mirror = true;
        this.setRotation(this.rightTop, 0.0F, 0.0F, 3.141592653589793F);
        this.container = new ModelRenderer(this, 0, 205);
        this.container.setRotationPoint(-10.0F, -12.0F, -14.0F);
        this.container.addBox(0.0F, 0.0F, 0.0F, 20, 13, 15);
        this.container.mirror = true;
	}

	public void setWheelRotation(float rot) {
		
		setRotation(wheel1a, rot, 0F, 0F);
		setRotation(wheel1b, rot, 0F, 0F);
		setRotation(wheel1c, rot, 0F, 0F);
		setRotation(wheel1d, rot, 0F, 0F);
		setRotation(wheel1e, rot, 0F, 0F);
		setRotation(wheel1f, rot, 0F, 0F);
		setRotation(wheel1g, rot, 0F, 0F);
		setRotation(wheel2a, rot, 0F, 0F);
		setRotation(wheel2b, rot, 0F, 0F);
		setRotation(wheel2c, rot, 0F, 0F);
		setRotation(wheel2d, rot, 0F, 0F);
		setRotation(wheel2e, rot, 0F, 0F);
		setRotation(wheel2f, rot, 0F, 0F);
		setRotation(wheel2g, rot, 0F, 0F);
		setRotation(wheel3a, rot, 0F, 0F);
		setRotation(wheel3b, rot, 0F, 0F);
		setRotation(wheel3c, rot, 0F, 0F);
		setRotation(wheel3d, rot, 0F, 0F);
		setRotation(wheel3e, rot, 0F, 0F);
		setRotation(wheel3f, rot, 0F, 0F);
		setRotation(wheel3g, rot, 0F, 0F);
		setRotation(wheel4a, rot, 0F, 0F);
		setRotation(wheel4b, rot, 0F, 0F);
		setRotation(wheel4c, rot, 0F, 0F);
		setRotation(wheel4d, rot, 0F, 0F);
		setRotation(wheel4e, rot, 0F, 0F);
		setRotation(wheel4f, rot, 0F, 0F);
		setRotation(wheel4g, rot, 0F, 0F);
		setRotation(wheel5a, rot, 0F, 0F);
		setRotation(wheel5b, rot, 0F, 0F);
		setRotation(wheel5c, rot, 0F, 0F);
		setRotation(wheel5d, rot, 0F, 0F);
		setRotation(wheel5e, rot, 0F, 0F);
		setRotation(wheel5f, rot, 0F, 0F);
		setRotation(wheel5g, rot, 0F, 0F);
		setRotation(wheel6a, rot, 0F, 0F);
		setRotation(wheel6b, rot, 0F, 0F);
		setRotation(wheel6c, rot, 0F, 0F);
		setRotation(wheel6d, rot, 0F, 0F);
		setRotation(wheel6e, rot, 0F, 0F);
		setRotation(wheel6f, rot, 0F, 0F);
		setRotation(wheel6g, rot, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);

		EntityCarBase car = (EntityCarBase) entity;

		setWheelRotation(car.updateWheelRotation(f5));

		setRotationAngles(f, f1, f2, f3, f4, f5, entity);

		bottom.render(f5);
		wheel1a.render(f5);
		wheel1b.render(f5);
		wheel1c.render(f5);
		wheel1d.render(f5);
		wheel1e.render(f5);
		wheel1f.render(f5);
		wheel1g.render(f5);
		wheel2a.render(f5);
		wheel2b.render(f5);
		wheel2c.render(f5);
		wheel2d.render(f5);
		wheel2e.render(f5);
		wheel2f.render(f5);
		wheel2g.render(f5);
		wheel3a.render(f5);
		wheel3b.render(f5);
		wheel3c.render(f5);
		wheel3d.render(f5);
		wheel3e.render(f5);
		wheel3f.render(f5);
		wheel3g.render(f5);
		wheel4a.render(f5);
		wheel4b.render(f5);
		wheel4c.render(f5);
		wheel4d.render(f5);
		wheel4e.render(f5);
		wheel4f.render(f5);
		wheel4g.render(f5);
		wheel5a.render(f5);
		wheel5b.render(f5);
		wheel5c.render(f5);
		wheel5d.render(f5);
		wheel5e.render(f5);
		wheel5f.render(f5);
		wheel5g.render(f5);
		wheel6a.render(f5);
		wheel6b.render(f5);
		wheel6c.render(f5);
		wheel6d.render(f5);
		wheel6e.render(f5);
		wheel6f.render(f5);
		wheel6g.render(f5);
		front.render(f5);
		frontWindow.render(f5);
		backWindow.render(f5);
		topLoader.render(f5);
		back.render(f5);
		right.render(f5);
		left.render(f5);
		leftFront.render(f5);
		rightFront.render(f5);
		rightTop.render(f5);
		leftTop.render(f5);
		topFront.render(f5);
		hood.render(f5);
		cabinLower.render(f5);
		
		if(con){
			container.render(f5);
		}
		
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
